### ISSUE TITLE
Not able to run multiline commands with "run: |"

### ISSUE THREAD

**Issue by s8sachin** [GabrielBB/xvfb-action#14]
Trying to run multiline gives out error
Command:
```
- name: yarn test
        uses: GabrielBB/xvfb-action@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run: |
            yarn package-ci
            yarn lint
            yarn tsc
```

Error:
```
error Command "package-ci\nyarn" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Error on os `macos-latest` and `ubuntu-latest`, but works fine on `windows-latest`
Any solution for this please ?

**Comment by hybridx** [comment]
Hi @s8sachin have you tried the following?
```yml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v2
  with:
    node-version: '14'
- name: yarn test
  uses: GabrielBB/xvfb-action@v1.2
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      run: |
        yarn package-ci
        yarn lint
        yarn tsc
```
