### ISSUE TITLE
Segfaults on windows starting ~2022/01/30

### ISSUE THREAD

**Issue by tlambert03** [GabrielBB/xvfb-action#25]
Yesterday, we started seeing all of our windows tests fail immediately with: `failed with exit code 3221225477`
(see for example: https://github.com/napari/napari/actions/runs/1768885019)

It appears that manually performing the os check, and not using this action on windows fixes it:
```yaml
      - name: Test with tox
        uses: GabrielBB/xvfb-action@v1
        if: runner.os == 'Linux'
        with:
          run: tox
```

see https://github.com/napari/napari/pull/4031/

Any thoughts on what might have changed in the last couple days that would break the "no-op" functionality on windows for this action?

**Comment by tlambert03** [comment]
@GabrielBB, any thoughts here?  I'm more than happy to help debug.  we've got a number of repos using this action, all of which are failing to pass on windows at the moment... so I've got some motivation to work on it :)
would you suspect an update to the `@actions/exec` pin would do anything?

**Comment by tlambert03** [comment]
i was able to narrow it down to a python environment related issue.  Something _has_ changed, but I'm not sure where.  
Whereas this used to work to test something (for example, with pytest-qt driving a headless Qt test):

```yaml
      - uses: GabrielBB/xvfb-action@v1
        with:
          run: pytest
```

in the last few days, it now requires:

```yaml
      - uses: GabrielBB/xvfb-action@v1
        with:
          run: python -m pytest
```

I think it's safe to say it's unrelated to xvfb-action, so will close this.
