### ISSUE TITLE
Unable to locate package xvfb

### ISSUE THREAD

**Issue by GeorgeXCV** [GabrielBB/xvfb-action#29]
```
 [command]/usr/bin/sudo apt-get install -y xvfb
| Reading package lists...
| Building dependency tree...
| Reading state information...
| E: Unable to locate package xvfb
[Daily Regression Tests/cypress-run]   ❗  ::error::The process '/usr/bin/sudo' failed with exit code 100
[Daily Regression Tests/cypress-run]   ❌  Failure - Main GabrielBB/xvfb-action@v1
```

```
name: Daily Regression Tests

on: [push]
  # schedule:
  #   #https://crontab.guru/#0_0_*_*_*
  #   - cron: "0 0 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    # Install NPM dependencies, cache them correctly
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18.7.0'
        cache: 'npm'
    - run: npm install
    # Run all Cypress tests
    - uses: GabrielBB/xvfb-action@v1
    - run: npm start -- --record --browser chrome
      env:
          # and pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```
