### ISSUE TITLE
String literals escaping

### ISSUE THREAD

**Issue by aminya** [GabrielBB/xvfb-action#3]
Is xvfb using another shell instead of bash?

I cannot escape my string literals while I have set bash as my default shell 
```yaml
defaults:
  run:
    shell: bash
```

```yaml
      - name: Run Graphical test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: julia --project -e 'include("deps/SnoopCompile/snoopi_bot.jl"); include("deps/SnoopCompile/snoopi_bench.jl");'
```
